<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<h1>Change password</h1>
<form id="changePassword" name="changePassword" method="post" action="/me/change-password">
    <div class="form-group">
        <label for="o_password">Old password:</label>
        <input type="text" name="o_password" class="form-control" id="user_password">
        <input type="hidden" id="user_id" name="id" value="<?= $id ?>">
    </div>
    <div class="form-group">
        <label for="new_password">New password:</label>
        <input type="text" name="new_password" class="form-control" id="user_password">
    </div>
    <div class="form-group">
        <label for="rep_password">Repeat password:</label>
        <input type="text" name="rep_password" class="form-control" id="user_password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</body>
</html>
