<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="script" src="js/form_ajax.js">
</head>
<body>
<h1>Formulier</h1>
<form id="registrationForm" name="registrationForm">
    <div class="form-group">
        <label for="id">ID</label>
        <input type="number" class="form-control" id="con_kla_id">
        <input type="hidden" id="dbfile" name="dbfile" value="contact"
    </div>
    <div class="form-group">
        <label for="naam">Achternaam</label>
        <input type="text" class="form-control" id="con_kla_naam">
    </div>
    <div class="form-group">
        <label for="voornaam">Voornaam</label>
        <input type="text" class="form-control" id="con_kla_voornaam">
    </div>
    <div class="form-group">
        <label for="postcode">Postcode</label>
        <input type="number" class="form-control" id="con_kla_postcode">
    </div>
    <div class="form-group">
        <label for="gemeente">Town</label>
        <input type="text" class="form-control" id="con_kla_gemeente">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</body>
</html>
