<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<h1>Profiel</h1>
<p>Email: <?= $email ?></p>
<p>Password: <?= $password ?></p>
<a href="/me/change-password/<?= $id ?>"><button>Wijzig wachtwoord</button></a>
<p></p>
</body>
</html>
